site:
  title: Continous Delivery
  url: /
  start_page: v0.11@continuous-delivery:en:index.adoc

content:
  sources:
    - url: ./
      start_paths: [versions/v0.11, versions/v0.10, versions/v0.9]

# Description: SUSE UI bundle
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'

output:
  dir: build/site