site:
  title: Continous Delivery
  url: /
  start_page: v0.12@continuous-delivery:en:index.adoc

content:
  sources:
    - url: https://github.com/rancher/fleet-product-docs.git
      branches: [head]
      start_paths: [versions/v0.12, versions/v0.11, versions/v0.10, versions/v0.9]


ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>
